### ISSUE TITLE
Error installing latest snapshot on Alfresco CE 5.1

### ISSUE THREAD

**Issue by richetdan** [ITDSystems/alvex-workflow-shortcut-dashlet#22]
Following the described procedure give this error on first startup, 
running the code embedded with alfresco sdk 2.2.0 whit the same alfresco version it works 

`2017-06-07 13:08:59,523 WARN [org.springframework.web.context.support.XmlWebApplicationContext] [localhost-startStop-1] Exception encountered during context initialization - cancelling refresh attempt
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'alvex-mapdb-key-value-store-provider' defined in class path resource [alfresco/module/utils/context/alvex-kvstore-context.xml]: Invocation of init method failed; nested exception is org.mapdb.DBException$GetVoid: Record does not exist, recid=1
 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1514)
 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:521)
 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:458)
 at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:293)
 at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:223)
 at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:290)
 at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:191)
 at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:636)
 at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:934)
 at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:479)
 at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:410)
 at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
 at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:112)
 at org.alfresco.web.app.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:63)
 at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:5016)
 at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5524)
 at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
 at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:901)
 at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:877)
 at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:649)
 at org.apache.catalina.startup.HostConfig.deployDescriptor(HostConfig.java:672)
 at org.apache.catalina.startup.HostConfig$DeployDescriptor.run(HostConfig.java:1859)
 at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
 at java.util.concurrent.FutureTask.run(Unknown Source)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
 at java.lang.Thread.run(Unknown Source)
Caused by: org.mapdb.DBException$GetVoid: Record does not exist, recid=1
 at org.mapdb.StoreWAL.getIndexVal(StoreWAL.kt:169)
 at org.mapdb.StoreWAL.get(StoreWAL.kt:499)
 at org.mapdb.DB.nameCatalogLoadLocked(DB.kt:350)
 at org.mapdb.DB.nameCatalogLoad(DB.kt:343)
 at org.mapdb.DB.nameCatalogVerifyGetMessages(DB.kt:1841)
 at org.mapdb.DB.<init>(DB.kt:272)
 at org.mapdb.DB.<init>(DB.kt:40)
 at org.mapdb.DBMaker$Maker.make(DBMaker.kt:477)
 at com.alvexcore.repo.kvstore.mapdb.MapDBKeyValueStoreProvider.initialize(MapDBKeyValueStoreProvider.java:37)
 at com.alvexcore.repo.kvstore.AbstractKeyValueStoreProvider.afterPropertiesSet(AbstractKeyValueStoreProvider.java:15)
 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1573)
 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1511)
 ... 26 more`

**Comment by aviriel** [comment]
What Alfresco version do you use?
Did you install alvex-utils together with workflow-permissions addon?
How did you install this addon? JAR, AMP, embeding into your project?

**Comment by richetdan** [comment]
Hi Oksana, I use Alfresco CE 5.1.e
I've got the error deploying the jars in the module/platform folder of an installed version as described in the wiki guide.
Using the same version as a dependency in my all-in-one project modules doesn't give the error.
Yes, I've installed alvex-utils and all the many required dependency jars too.

**Comment by aviriel** [comment]
Sorry, but I cannot reproduce your issue. I don't get any errors while installing workflow-permissions + utils in JAR on the Alfresco 5.1 and 5.2

**Comment by richetdan** [comment]
I've got the error on a Windows 7 environement. Don't know if it's relevant. 
The developing stage with the maven sdk was on linux.
Thank you anyway.

**Comment by aviriel** [comment]
Then how do you build it? Do you simply clone the repository, build it with `mvn -P make-jar clean install` and then copy JARs to Alfresco? Are you sure you also copy alvex-utils JARs to Alfresco?

**Comment by richetdan** [comment]
yes, downloaded the zip from github, unpacked and builded (I've also tried with the precompiled ones).
copied all the jars and dependencies in module/platform and module/share folders and restarted tomcat. 
Yes i'm sure to have copied the alvex-utils. 
However doesn't matter, I've resolved my requirements in other way. It's just for contribution because the addon is very nice and powerful.
When I will have time I will try over a Linux platform in order to understand if it depends on the SO.
Thanks.

**Comment by aviriel** [comment]
Ok, thank you. We use in on Linux as usual and I cannot get such error in all cases on Alfresco 201702.

**Comment by richetdan** [comment]
I can confirm that following the same identical procedure on a clean installation of Alfresco 201605 on Ubuntu Linux it works like a charm! I don't know wtf with Windows 7. Thanks.

**Comment by aviriel** [comment]
Ok, let's think that it's closed :)
